baseURL: "https://vedantbairagi.github.io"
languageCode: "en-us"
title: "Vedant Bairagi"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Vedant Bairagi"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.jpg"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # light

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    #align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    #brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    #brandName: "Profile" # Brand name for the brand | default is the title variable
     menus:
        disableAbout: false
        disableExperience: false
        disableEducation: false
        disableProjects: false
        disableAchievements: true
        disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello There, I'm"
    title: "Vedant Bairagi"
    subtitle: "I like to learn and understand new technologies."
    content: "A passionate computer engineering student interested in Data Science, NLP and DevOps"
    image: 
    button:
      enable: true
      name: "Resume"
      url: "#" # add pdf here
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/vedantbairagi/
        - icon: fab fa-kaggle
          url: https://www.kaggle.com/vedant8390rex
      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/try1.png"
    content: |-
      I am a Computer Engineering student having interest in Data Science and Analytics. I am pursuing my B.Tech with Honors in Data Science from the third oldest engineering
      college of India, COEP Technological University. 

      Currently I am working as a Research Intern at TRDDC, Pune.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Tensorflow"
        - "Docker"
        - "Selenium"
        - "Jupyter"
        - "Streamlit"
        - "Gradio"

  # Experience
  experience:
    enable: true
    items:
      
      - job: "Research Intern"
        company: "TCS Research"
        companyUrl: "https://www.tcs.com/research-and-innovation"
        date: "May 2022 - Jul 2022"
        content: "Remote Internship focusing on Deep Learning in the Natural Language Processing of Hindi.\n\
                 Project titled - Timeline generation using Event Extraction in Hindi"

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Technology in Computer Engineering"
        school:
          name: "COEP Technological University"
          url: "https://www.coep.org.in/"
        date: "2019 - 2023"
        PercentageGPA: "8.59 out of 10 (Current)"


        content: |-
          Extracurricular Activities
            - I was part of various societies, clubs and fests like CSI, Streetplay Team and Impressions, Zest.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Junior College"
        school:
          name: "HPT Arts and RYK Science College"
          url: "https://hptrykcollege.com/"
        PercentageGPA: "85%"
        date: "2018"
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Dominant Color Extractor
        content: My first Gradio App. Using this you can extract dominant colors from an image.\nI have used KMeans Clustering for the extraction.
        image: /dom.png
        featured:
          name: Demo
          link: https://dominant-color-extractor.herokuapp.com/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/vedantBairagi
          

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: vedant903121@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/vedantBairagi
      linkedin: https://linkedin.com/vedantbairagi
      #twitter: https://twitter.com
      instagram: https://instagram.com/vedantbairagi
      #facebook: https://facebook.com
      kaggle: https://www.kaggle.com/vedant8390rex

